import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { dark } from "@clerk/themes";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });
const chillaxRegular = localFont({
  src: [
    {
      path: "../public/fonts/Chillax-Regular.otf",
      weight: "normal",
    },
  ],
  variable: "--font-chillax-regular",
});
const chillaxBold = localFont({
  src: [
    {
      path: "../public/fonts/Chillax-Bold.otf",
      weight: "bold",
    },
  ],
  variable: "--font-chillax-bold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-background font-chillaxRegular ${chillaxBold.className} ${chillaxRegular.className}  ${inter.className}`}
      >
        {children}
      </body>
    </html>
  );
}
