import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import Navbar from "@/components/general/navbar";

const inter = Inter({ subsets: ["latin"] });
const chillaxRegular = localFont({
  src: [
    {
      path: "../public/fonts/Chillax-Regular.otf",
      weight: "normal",
    },
  ],
  variable: "--font-chillaxRegular",
});
const chillaxBold = localFont({
  src: [
    {
      path: "../public/fonts/Chillax-Bold.otf",
      weight: "bold",
    },
  ],
  variable: "--font-chillaxBold",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        //  TODO COMEBACK AND FIX THE ISSUE FOR THE FONT WEIGHT, OR JUST USE ANOTHER FONT, NOT LOCALLY ONES
        className={`bg-background text-textMain ${chillaxBold.className}  ${chillaxRegular.className}  ${inter.className}`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
